config/routes.rb
ChristmasGiftExchange::Application.routes.draw do

  resources :index, only: [:index]

  resources :users, only: [:new, :create, :update, :show] do
    resources :lists, only: [:index, :create], controller: "lists" do
      resources :items, only: [:create, :destroy]
    end
  end

  get 'password', to: 'users#password'
  post 'sign_in', to: 'users#sign_in'
  post 'sign_out', to: 'users#sign_out'
  post 'reset_password', to: 'users#reset_password'

  root :to => 'index#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :item, :list_id
  belongs_to :list
  validates_presence_of :item
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :user_id, :paired_user_id
  belongs_to :user
  has_many :items

  def any_items?
    self.items.count != 0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :password, :family_group, :paired_list_id

  has_one :list

  validates_presence_of :first_name
  validates_uniqueness_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :password, :on => :create
  validates_presence_of :family_group
  
  has_secure_password

  def paired?
    self.paired_list_id != nil
  end

  def paired_with_list
    paired_list = List.find(self.paired_list_id)
  end

  def paired_with
    paired_list = List.find(self.paired_list_id)
    User.find(paired_list.user_id).first_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    @user = User.new
  end

end

app/controllers/items_controller.rb
class ItemsController < IndexController

  def create
    user = User.find(params[:user_id])
    list = List.find(params[:list_id])
    item = Item.new(params[:item])
    item.list_id = list.id
    if item.save
      redirect_to user_lists_path(user.id, list.id)
    else
      flash[:add_item_error] = item.errors.full_messages.join(', ')
      redirect_to user_lists_path(user.id, list.id)
    end
  end

  def destroy
    user = User.find(params[:user_id])
    list = List.find(params[:list_id])
    item = Item.find(params[:id])
    item.destroy
    redirect_to user_lists_path(user.id, list.id)
  end

end

app/controllers/lists_controller.rb
class ListsController < IndexController

  def index
    @user = User.find(params[:user_id])
    @list = List.find_by_user_id(@user.id)
    @item = Item.new
  end

  def create
    user = User.find(params[:user_id])
    list = List.new(params[:list])
    list.user_id = user.id
    if list.save
      redirect_to user_lists_path(list.user_id)
    else
      redirect_to new_user_list_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < IndexController

  def new
    redirect_to user_lists_path(session[:user_id]) if session[:user_id]
    @new_user = User.new
    @sign_in_user = User.new
  end

  def create
    user = User.new(params[:user])
    if user.save
      session[:user_id] = user.id
      redirect_to user_lists_path(user.id)
    else
      flash[:sign_up_error] = user.errors.full_messages.join(', ')
      redirect_to root_path
    end
  end

  def sign_in
    sign_in_name = params[:user][:first_name].capitalize
    user = User.find_by_first_name(sign_in_name)
    if user.email == params[:user][:email] && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_lists_path(user.id)
    else
      flash[:sign_in_msg] = "Please try again."
      redirect_to root_path
    end
  end

  def sign_out
    session[:user_id] = nil
    redirect_to root_path
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(params[:user])
      redirect_to root_path
    else
      flash[:update_error] = user.errors.full_messages.join(', ')
      redirect_to user_path(user.id)
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def password
    @user = User.new
  end

  def reset_password
    user = User.find_by_first_name(params[:user][:first_name])
    if user.email == params[:user][:email] && params[:user][:password] == params[:user][:confirm_password]
      user.update_attributes(password: params[:user][:password] )
      flash[:sign_in_msg] = "Password updated! Please sign in."
      redirect_to root_path
    else
      flash[:reset_password_msg] = "Please try again."
      redirect_to password_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def days_until_christmas
    christmas = Time.local(2013, 12, 25)
    ((christmas - Time.now) / 86400).ceil
  end

  def countdown_before_christmas(countdown)
    if countdown > 1
      "#{countdown} Days Until Christmas!"
    else
      "#{countdown} Day Until Christmas!"
    end
  end

  def countdown_after_christmas
    "Hope You Had a Merry Christmas!"
  end

  def countdown_message
    if days_until_christmas > 0
      countdown_before_christmas(days_until_christmas)
    else
      countdown_after_christmas
    end
  end

  def signed_in?(user)
    session[:user_id] == user.id
  end

end

app/views/index/index.html.haml
%h1.text-center.main-title Christmas Family Name Draw

.content
  .col-sm-1.side
  .col-sm-6.center-block
    #intro-text
      Placeholder for Intro Text
  .col-sm-4.center-block
    .index-form
      %h3.text-center Sign In
      = form_for @user do |f|
        .form-group
          = f.text_field :first_name, placeholder: "First Name", class: "form-control"
        .form-group
          = f.email_field :email, placeholder: "Email Address", class: "form-control"
        .form-group
          = f.password_field :password, placeholder: "Password", class: "form-control"
        .form-group
          = f.submit "Sign In", class: "form-control"
    .index-form
      %h3.text-center Reset Your Account
      Placeholder for reset form
  .col-sm-1.side

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Family Christmas Gift Name Draw
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Lily+Script+One"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body{class: "#{params[:controller]}-#{params[:action]}"}
    .container-fluid
      = yield

app/views/lists/index.html.erb
<div class="container">
	<% if signed_in?(@user) %>
		<h1 class="main-title">Welcome, <%= @user.first_name.capitalize %>!</h1>

		
		<div class="lists">
			<% if @user.paired? %>
				<h2 class="list-title"><%= "#{@user.paired_with}'s List" %></h2>

				<% if @user.paired_with_list.any_items? %>
					<ul class="christmas-list">
						<% @user.paired_with_list.items.each do |item| %>
							<li><%= item.item %></li>
						<% end %>
					</ul>
				<% else %>
					<h2 class="list-title">No items added yet.</h2>
				<% end %>

			<% else %>
				<h2 class="list-title">Sorry, Not Paired Yet</h2>
			<% end %>
		</div>

		<div class="lists">
			<h2 class="list-title">Your List</h2>

			<% if @user.list %>
				<ul class="christmas-list">
				<% @user.list.items.each do |item| %>
					<li> <%= item.item %> <%= link_to "Remove from list", user_list_item_path(@user.id, @user.list.id, item.id), method: "delete", class: "links", data: { confirm: "Remove #{item.item} from your list?" } %></li>
				<% end %>
				</ul>

				<%= form_for [@user, @list, @item], url: user_list_items_path(@user.id, @list.id) do |f| %>
					<%= f.text_field :item %>
					<%= f.submit "Add Item" %>
				<% end %>
				<%= flash[:add_item_error] %>

			<% else %>
				<p class="create-list"><%= link_to "Create Christmas List", {controller: "lists", action: "create" }, method: "post" %></p>
			<% end %>
		</div>

		<p class="links"><%= link_to "Update Info", user_path(@user.id)%></p>
		<p class="links"><%= link_to "Sign Out", {controller: "users", action: "sign_out"}, method: "post" %></p>

	<% else %>
		<h1 id="not_signed_in_top">Ho! Ho! Ho!</h1>
		<h2 id="not_signed_in_bottom">You need to be signed in to see this!</h2>
		<p class="links"><%= link_to "Return Home", root_path%></p>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1 class="main-title">Christmas Name Draw</h1>

	<h2 id="countdown"><%= countdown_message %></h2>

	<div id="sign_in">
		<h3 class="sign_up_sign_in">Sign Up</h1>

		<%= form_for @new_user do |f| %>
			<%= f.label "First Name" %><br/>
			<%= f.text_field :first_name, class: "form_field", required: true %><br/>
			<%= f.label "Last Name" %><br/>
			<%= f.text_field :last_name, class: "form_field", required: true  %><br/>
			<%= f.label "Email" %><br/>
			<%= f.text_field :email, class: "form_field", required: true  %><br/>
			<%= f.label "Password" %><br/>
			<%= f.password_field :password, class: "form_field", required: true  %><br/>
			<%= f.label "Family Group" %><br/>
			<%= f.select :family_group, ['Dragseth', 'King', 'Nugent/Lim/Saito'] %><br/>
			<%= f.submit "Sign Up", class: "form_button"%>
		<% end %>
		<span class="error_flash"><%= flash[:sign_up_error] %></span>
	</div>

	<div id="sign_up">
		<h3 class="sign_up_sign_in">Sign In</h1>

		<%= form_for @sign_in_user, url: {action: "sign_in"} do |f| %>
			<%= f.label "First Name" %><br/>
			<%= f.text_field :first_name, class: "form_field", id: "sign_in_first_name", required: true %><br/>
			<%= f.label "Email" %><br/>
			<%= f.text_field :email, class: "form_field", id: "sign_in_email", required: true %><br/>
			<%= f.label "Password" %><br/>
			<%= f.password_field :password, class: "form_field", id: "sign_in_password", required: true %><br/>
			<%= f.submit "Sign In", class: "form_button"%>
		<% end %>
		<span class="error_flash"><%= flash[:sign_in_msg] %></span>
		<p class="links"><%= link_to "Update Your Password", password_path %></p>
	</div>
</div>

app/views/users/password.html.erb
<h1 class="main-title">Update Your Password</h1>

<div id="reset_password">
	<%= form_for @user, url: {action: "reset_password"} do |f| %>
		<%= f.label "First Name" %><br/>
		<%= f.text_field :first_name, id: "first_name", required: true %><br/>
		<%= f.label "Email" %><br/>
		<%= f.text_field :email, id: "email", required: true %><br/>
		<%= f.label "New Password" %><br/>
		<%= f.password_field :password, id: "password", required: true %><br/>
		<%= f.label "Confirm Password" %><br/>
		<%= f.password_field :confirm_password, id: "confirm_password", required: true %><br/>
		<%= f.submit "Update Password" %>
	<% end %>

	<span class="error_flash"><%= flash[:reset_password_msg] %></span>
</div>

<p class="links"><%= link_to "Return Home", root_path%></p>

app/views/users/show.html.erb
<% if signed_in?(@user) %>
	<h1 class="main-title">Update Info</h1>

	<div class="lists">
		<%= form_for @user, url: user_path, method: :put do |f| %>
			<%= f.label "First Name" %><br/>
			<%= f.text_field :first_name, class: "form_field" %><br/>
			<%= f.label "Last Name" %><br/>
			<%= f.text_field :last_name, class: "form_field"  %><br/>
			<%= f.label "Email" %><br/>
			<%= f.text_field :email, class: "form_field"  %><br/>
			<%= f.label "Family Group" %><br/>
			<%= f.select :family_group, ['Dragseth', 'King', 'Nugent/Lim/Saito'] %><br/>
			<%= f.submit "Update Info", class: "form_button"%>
		<% end %>
		<span class="error_flash"><%= flash[:update_error] %></span>
	</div>
	<p class="links"><%= link_to "Back To Lists", user_lists_path(@user.id)%></p>
<% else %>
	<h1 id="not_signed_in_top">Ho! Ho! Ho!</h1>
	<h2 id="not_signed_in_bottom">You need to be signed in to see this!</h2>
	<p class="links"><%= link_to "Return Home", root_path%></p>
<% end %>